# Generated by Django 3.1.3 on 2022-04-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('가게이름', models.CharField(max_length=100)),
                ('주소', models.CharField(max_length=100)),
                ('위도', models.FloatField(default=0.0)),
                ('경도', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('관광안내소명', models.CharField(max_length=100)),
                ('소재지도로명주소', models.CharField(max_length=100)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
            ],
            options={
                'db_table': 'tour_info',
            },
        ),
        migrations.CreateModel(
            name='TourMotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('지번주소', models.CharField(max_length=100)),
                ('사업장명', models.CharField(max_length=100)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
            ],
            options={
                'db_table': 'tour_motel',
            },
        ),
        migrations.CreateModel(
            name='TourStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('검색키워드', models.CharField(max_length=100)),
                ('지번주소', models.CharField(max_length=100)),
                ('경도', models.FloatField()),
                ('위도', models.FloatField()),
            ],
            options={
                'db_table': 'tour_street',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
    ]
